-- Fill address_format and phone_format for all countries.
-- address_format: standard template (identical to the code fallback in
-- catalog/controller/account/order.php), only empty cells are filled.
-- phone_format: libphonenumber primary mobile format per territory (X = one
-- digit, other chars are literal — see help_phone_format). Only territories
-- with a fixed national number length get a mask; variable-length plans
-- (DE, IT, BR, AT, ...) and territories without numbering data (UM, AN)
-- intentionally keep phone_format empty so checkout falls back to the
-- lenient 3-32 digit check instead of rejecting valid numbers.
-- Idempotent: only empty cells are updated, re-running is a no-op.

-- Address formats (base table, empty only)
UPDATE `oc_country` SET `address_format` = '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{city} {postcode}\r\n{zone}\r\n{country}'
WHERE `address_format` = '';

-- Phone masks (base table, empty only)
UPDATE `oc_country` SET `phone_format` = '+93 XX XXX XXXX' WHERE `country_id` = 1 AND `phone_format` = ''; -- Afghanistan (AF)
UPDATE `oc_country` SET `phone_format` = '+355 XX XXX XXXX' WHERE `country_id` = 2 AND `phone_format` = ''; -- Albania (AL)
UPDATE `oc_country` SET `phone_format` = '+213 XXX XX XX XX' WHERE `country_id` = 3 AND `phone_format` = ''; -- Algeria (DZ)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 4 AND `phone_format` = ''; -- American Samoa (AS)
UPDATE `oc_country` SET `phone_format` = '+244 XXX XXX XXX' WHERE `country_id` = 6 AND `phone_format` = ''; -- Angola (AO)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 7 AND `phone_format` = ''; -- Anguilla (AI)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 9 AND `phone_format` = ''; -- Antigua and Barbuda (AG)
UPDATE `oc_country` SET `phone_format` = '+374 XX XXXXXX' WHERE `country_id` = 11 AND `phone_format` = ''; -- Armenia (AM)
UPDATE `oc_country` SET `phone_format` = '+297 XXX XXXX' WHERE `country_id` = 12 AND `phone_format` = ''; -- Aruba (AW)
UPDATE `oc_country` SET `phone_format` = '+61 XXX XXX XXX' WHERE `country_id` = 13 AND `phone_format` = ''; -- Australia (AU)
UPDATE `oc_country` SET `phone_format` = '+994 XX XXX XX XX' WHERE `country_id` = 15 AND `phone_format` = ''; -- Azerbaijan (AZ)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 16 AND `phone_format` = ''; -- Bahamas (BS)
UPDATE `oc_country` SET `phone_format` = '+973 XXXX XXXX' WHERE `country_id` = 17 AND `phone_format` = ''; -- Bahrain (BH)
UPDATE `oc_country` SET `phone_format` = '+880 XXXX-XXXXXX' WHERE `country_id` = 18 AND `phone_format` = ''; -- Bangladesh (BD)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 19 AND `phone_format` = ''; -- Barbados (BB)
UPDATE `oc_country` SET `phone_format` = '+375 XX XXX-XX-XX' WHERE `country_id` = 20 AND `phone_format` = ''; -- Belarus (BY)
UPDATE `oc_country` SET `phone_format` = '+32 XXX XX XX XX' WHERE `country_id` = 21 AND `phone_format` = ''; -- Belgium (BE)
UPDATE `oc_country` SET `phone_format` = '+501 XXX-XXXX' WHERE `country_id` = 22 AND `phone_format` = ''; -- Belize (BZ)
UPDATE `oc_country` SET `phone_format` = '+229 XX XX XX XX XX' WHERE `country_id` = 23 AND `phone_format` = ''; -- Benin (BJ)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 24 AND `phone_format` = ''; -- Bermuda (BM)
UPDATE `oc_country` SET `phone_format` = '+975 XX XX XX XX' WHERE `country_id` = 25 AND `phone_format` = ''; -- Bhutan (BT)
UPDATE `oc_country` SET `phone_format` = '+591 XXXXXXXX' WHERE `country_id` = 26 AND `phone_format` = ''; -- Bolivia (BO)
UPDATE `oc_country` SET `phone_format` = '+267 XX XXX XXX' WHERE `country_id` = 28 AND `phone_format` = ''; -- Botswana (BW)
UPDATE `oc_country` SET `phone_format` = '+246 XXX XXXX' WHERE `country_id` = 31 AND `phone_format` = ''; -- British Indian Ocean Territory (IO)
UPDATE `oc_country` SET `phone_format` = '+673 XXX XXXX' WHERE `country_id` = 32 AND `phone_format` = ''; -- Brunei Darussalam (BN)
UPDATE `oc_country` SET `phone_format` = '+226 XX XX XX XX' WHERE `country_id` = 34 AND `phone_format` = ''; -- Burkina Faso (BF)
UPDATE `oc_country` SET `phone_format` = '+257 XX XX XX XX' WHERE `country_id` = 35 AND `phone_format` = ''; -- Burundi (BI)
UPDATE `oc_country` SET `phone_format` = '+237 X XX XX XX XX' WHERE `country_id` = 37 AND `phone_format` = ''; -- Cameroon (CM)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 38 AND `phone_format` = ''; -- Canada (CA)
UPDATE `oc_country` SET `phone_format` = '+238 XXX XX XX' WHERE `country_id` = 39 AND `phone_format` = ''; -- Cape Verde (CV)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 40 AND `phone_format` = ''; -- Cayman Islands (KY)
UPDATE `oc_country` SET `phone_format` = '+236 XX XX XX XX' WHERE `country_id` = 41 AND `phone_format` = ''; -- Central African Republic (CF)
UPDATE `oc_country` SET `phone_format` = '+235 XX XX XX XX' WHERE `country_id` = 42 AND `phone_format` = ''; -- Chad (TD)
UPDATE `oc_country` SET `phone_format` = '+56 X XXXX XXXX' WHERE `country_id` = 43 AND `phone_format` = ''; -- Chile (CL)
UPDATE `oc_country` SET `phone_format` = '+86 XXX XXXX XXXX' WHERE `country_id` = 44 AND `phone_format` = ''; -- China (CN)
UPDATE `oc_country` SET `phone_format` = '+61 XXXXXXXXX' WHERE `country_id` = 45 AND `phone_format` = ''; -- Christmas Island (CX)
UPDATE `oc_country` SET `phone_format` = '+61 XXXXXXXXX' WHERE `country_id` = 46 AND `phone_format` = ''; -- Cocos (Keeling) Islands (CC)
UPDATE `oc_country` SET `phone_format` = '+57 XXX XXXXXXX' WHERE `country_id` = 47 AND `phone_format` = ''; -- Colombia (CO)
UPDATE `oc_country` SET `phone_format` = '+269 XXX XX XX' WHERE `country_id` = 48 AND `phone_format` = ''; -- Comoros (KM)
UPDATE `oc_country` SET `phone_format` = '+242 XX XXX XXXX' WHERE `country_id` = 49 AND `phone_format` = ''; -- Congo (CG)
UPDATE `oc_country` SET `phone_format` = '+682 XX XXX' WHERE `country_id` = 50 AND `phone_format` = ''; -- Cook Islands (CK)
UPDATE `oc_country` SET `phone_format` = '+506 XXXX XXXX' WHERE `country_id` = 51 AND `phone_format` = ''; -- Costa Rica (CR)
UPDATE `oc_country` SET `phone_format` = '+225 XX XX XX XXXX' WHERE `country_id` = 52 AND `phone_format` = ''; -- Cote D'Ivoire (CI)
UPDATE `oc_country` SET `phone_format` = '+53 X XXXXXXX' WHERE `country_id` = 54 AND `phone_format` = ''; -- Cuba (CU)
UPDATE `oc_country` SET `phone_format` = '+357 XX XXXXXX' WHERE `country_id` = 55 AND `phone_format` = ''; -- Cyprus (CY)
UPDATE `oc_country` SET `phone_format` = '+420 XXX XXX XXX' WHERE `country_id` = 56 AND `phone_format` = ''; -- Czech Republic (CZ)
UPDATE `oc_country` SET `phone_format` = '+45 XX XX XX XX' WHERE `country_id` = 57 AND `phone_format` = ''; -- Denmark (DK)
UPDATE `oc_country` SET `phone_format` = '+253 XX XX XX XX' WHERE `country_id` = 58 AND `phone_format` = ''; -- Djibouti (DJ)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 59 AND `phone_format` = ''; -- Dominica (DM)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 60 AND `phone_format` = ''; -- Dominican Republic (DO)
UPDATE `oc_country` SET `phone_format` = '+670 XXXX XXXX' WHERE `country_id` = 61 AND `phone_format` = ''; -- East Timor (TL)
UPDATE `oc_country` SET `phone_format` = '+593 XX XXX XXXX' WHERE `country_id` = 62 AND `phone_format` = ''; -- Ecuador (EC)
UPDATE `oc_country` SET `phone_format` = '+20 XX XXXXXXXX' WHERE `country_id` = 63 AND `phone_format` = ''; -- Egypt (EG)
UPDATE `oc_country` SET `phone_format` = '+503 XXXX XXXX' WHERE `country_id` = 64 AND `phone_format` = ''; -- El Salvador (SV)
UPDATE `oc_country` SET `phone_format` = '+240 XXX XXX XXX' WHERE `country_id` = 65 AND `phone_format` = ''; -- Equatorial Guinea (GQ)
UPDATE `oc_country` SET `phone_format` = '+291 X XXX XXX' WHERE `country_id` = 66 AND `phone_format` = ''; -- Eritrea (ER)
UPDATE `oc_country` SET `phone_format` = '+251 XX XXX XXXX' WHERE `country_id` = 68 AND `phone_format` = ''; -- Ethiopia (ET)
UPDATE `oc_country` SET `phone_format` = '+500 XXXXX' WHERE `country_id` = 69 AND `phone_format` = ''; -- Falkland Islands (Malvinas) (FK)
UPDATE `oc_country` SET `phone_format` = '+298 XX XX XX' WHERE `country_id` = 70 AND `phone_format` = ''; -- Faroe Islands (FO)
UPDATE `oc_country` SET `phone_format` = '+679 XXX XXXX' WHERE `country_id` = 71 AND `phone_format` = ''; -- Fiji (FJ)
UPDATE `oc_country` SET `phone_format` = '+33 X XX XX XX XX' WHERE `country_id` = 74 AND `phone_format` = ''; -- France, Metropolitan (FR)
UPDATE `oc_country` SET `phone_format` = '+594 XXX XX XX XX' WHERE `country_id` = 75 AND `phone_format` = ''; -- French Guiana (GF)
UPDATE `oc_country` SET `phone_format` = '+689 XX XX XX XX' WHERE `country_id` = 76 AND `phone_format` = ''; -- French Polynesia (PF)
UPDATE `oc_country` SET `phone_format` = '+995 XXX XX XX XX' WHERE `country_id` = 80 AND `phone_format` = ''; -- Georgia (GE)
UPDATE `oc_country` SET `phone_format` = '+233 XX XXX XXXX' WHERE `country_id` = 82 AND `phone_format` = ''; -- Ghana (GH)
UPDATE `oc_country` SET `phone_format` = '+350 XXXXXXXX' WHERE `country_id` = 83 AND `phone_format` = ''; -- Gibraltar (GI)
UPDATE `oc_country` SET `phone_format` = '+30 XXX XXX XXXX' WHERE `country_id` = 84 AND `phone_format` = ''; -- Greece (GR)
UPDATE `oc_country` SET `phone_format` = '+299 XX XX XX' WHERE `country_id` = 85 AND `phone_format` = ''; -- Greenland (GL)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 86 AND `phone_format` = ''; -- Grenada (GD)
UPDATE `oc_country` SET `phone_format` = '+590 XXX XX XX XX' WHERE `country_id` = 87 AND `phone_format` = ''; -- Guadeloupe (GP)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 88 AND `phone_format` = ''; -- Guam (GU)
UPDATE `oc_country` SET `phone_format` = '+502 XXXX XXXX' WHERE `country_id` = 89 AND `phone_format` = ''; -- Guatemala (GT)
UPDATE `oc_country` SET `phone_format` = '+224 XXX XX XX XX' WHERE `country_id` = 90 AND `phone_format` = ''; -- Guinea (GN)
UPDATE `oc_country` SET `phone_format` = '+245 XXX XXX XXX' WHERE `country_id` = 91 AND `phone_format` = ''; -- Guinea-Bissau (GW)
UPDATE `oc_country` SET `phone_format` = '+592 XXX XXXX' WHERE `country_id` = 92 AND `phone_format` = ''; -- Guyana (GY)
UPDATE `oc_country` SET `phone_format` = '+509 XX XX XXXX' WHERE `country_id` = 93 AND `phone_format` = ''; -- Haiti (HT)
UPDATE `oc_country` SET `phone_format` = '+504 XXXX-XXXX' WHERE `country_id` = 95 AND `phone_format` = ''; -- Honduras (HN)
UPDATE `oc_country` SET `phone_format` = '+852 XXXX XXXX' WHERE `country_id` = 96 AND `phone_format` = ''; -- Hong Kong (HK)
UPDATE `oc_country` SET `phone_format` = '+36 XX XXX XXXX' WHERE `country_id` = 97 AND `phone_format` = ''; -- Hungary (HU)
UPDATE `oc_country` SET `phone_format` = '+91 XXXXX XXXXX' WHERE `country_id` = 99 AND `phone_format` = ''; -- India (IN)
UPDATE `oc_country` SET `phone_format` = '+98 XXX XXX XXXX' WHERE `country_id` = 101 AND `phone_format` = ''; -- Iran (Islamic Republic of) (IR)
UPDATE `oc_country` SET `phone_format` = '+964 XXX XXX XXXX' WHERE `country_id` = 102 AND `phone_format` = ''; -- Iraq (IQ)
UPDATE `oc_country` SET `phone_format` = '+353 XX XXX XXXX' WHERE `country_id` = 103 AND `phone_format` = ''; -- Ireland (IE)
UPDATE `oc_country` SET `phone_format` = '+972 XX-XXX-XXXX' WHERE `country_id` = 104 AND `phone_format` = ''; -- Israel (IL)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 106 AND `phone_format` = ''; -- Jamaica (JM)
UPDATE `oc_country` SET `phone_format` = '+81 XX-XXXX-XXXX' WHERE `country_id` = 107 AND `phone_format` = ''; -- Japan (JP)
UPDATE `oc_country` SET `phone_format` = '+962 X XXXX XXXX' WHERE `country_id` = 108 AND `phone_format` = ''; -- Jordan (JO)
UPDATE `oc_country` SET `phone_format` = '+7 XXX XXX XX XX' WHERE `country_id` = 109 AND `phone_format` = ''; -- Kazakhstan (KZ)
UPDATE `oc_country` SET `phone_format` = '+254 XXX XXXXXX' WHERE `country_id` = 110 AND `phone_format` = ''; -- Kenya (KE)
UPDATE `oc_country` SET `phone_format` = '+686 XXXXXXXX' WHERE `country_id` = 111 AND `phone_format` = ''; -- Kiribati (KI)
UPDATE `oc_country` SET `phone_format` = '+850 XXX XXX XXXX' WHERE `country_id` = 112 AND `phone_format` = ''; -- North Korea (KP)
UPDATE `oc_country` SET `phone_format` = '+965 XXX XXXXX' WHERE `country_id` = 114 AND `phone_format` = ''; -- Kuwait (KW)
UPDATE `oc_country` SET `phone_format` = '+996 XXX XXX XXX' WHERE `country_id` = 115 AND `phone_format` = ''; -- Kyrgyzstan (KG)
UPDATE `oc_country` SET `phone_format` = '+371 XX XXX XXX' WHERE `country_id` = 117 AND `phone_format` = ''; -- Latvia (LV)
UPDATE `oc_country` SET `phone_format` = '+266 XXXX XXXX' WHERE `country_id` = 119 AND `phone_format` = ''; -- Lesotho (LS)
UPDATE `oc_country` SET `phone_format` = '+218 XX-XXXXXXX' WHERE `country_id` = 121 AND `phone_format` = ''; -- Libyan Arab Jamahiriya (LY)
UPDATE `oc_country` SET `phone_format` = '+370 XXX XXXXX' WHERE `country_id` = 123 AND `phone_format` = ''; -- Lithuania (LT)
UPDATE `oc_country` SET `phone_format` = '+352 XXX XXX XXX' WHERE `country_id` = 124 AND `phone_format` = ''; -- Luxembourg (LU)
UPDATE `oc_country` SET `phone_format` = '+853 XXXX XXXX' WHERE `country_id` = 125 AND `phone_format` = ''; -- Macau (MO)
UPDATE `oc_country` SET `phone_format` = '+389 XX XXX XXX' WHERE `country_id` = 126 AND `phone_format` = ''; -- FYROM (MK)
UPDATE `oc_country` SET `phone_format` = '+261 XX XX XXX XX' WHERE `country_id` = 127 AND `phone_format` = ''; -- Madagascar (MG)
UPDATE `oc_country` SET `phone_format` = '+265 XXX XX XX XX' WHERE `country_id` = 128 AND `phone_format` = ''; -- Malawi (MW)
UPDATE `oc_country` SET `phone_format` = '+960 XXX-XXXX' WHERE `country_id` = 130 AND `phone_format` = ''; -- Maldives (MV)
UPDATE `oc_country` SET `phone_format` = '+223 XX XX XX XX' WHERE `country_id` = 131 AND `phone_format` = ''; -- Mali (ML)
UPDATE `oc_country` SET `phone_format` = '+356 XXXX XXXX' WHERE `country_id` = 132 AND `phone_format` = ''; -- Malta (MT)
UPDATE `oc_country` SET `phone_format` = '+692 XXX-XXXX' WHERE `country_id` = 133 AND `phone_format` = ''; -- Marshall Islands (MH)
UPDATE `oc_country` SET `phone_format` = '+596 XXX XX XX XX' WHERE `country_id` = 134 AND `phone_format` = ''; -- Martinique (MQ)
UPDATE `oc_country` SET `phone_format` = '+222 XX XX XX XX' WHERE `country_id` = 135 AND `phone_format` = ''; -- Mauritania (MR)
UPDATE `oc_country` SET `phone_format` = '+230 XXXX XXXX' WHERE `country_id` = 136 AND `phone_format` = ''; -- Mauritius (MU)
UPDATE `oc_country` SET `phone_format` = '+262 XXXXXXXXX' WHERE `country_id` = 137 AND `phone_format` = ''; -- Mayotte (YT)
UPDATE `oc_country` SET `phone_format` = '+52 XXX XXX XXXX' WHERE `country_id` = 138 AND `phone_format` = ''; -- Mexico (MX)
UPDATE `oc_country` SET `phone_format` = '+691 XXX XXXX' WHERE `country_id` = 139 AND `phone_format` = ''; -- Micronesia, Federated States of (FM)
UPDATE `oc_country` SET `phone_format` = '+373 XXX XX XXX' WHERE `country_id` = 140 AND `phone_format` = ''; -- Moldova, Republic of (MD)
UPDATE `oc_country` SET `phone_format` = '+976 XXXX XXXX' WHERE `country_id` = 142 AND `phone_format` = ''; -- Mongolia (MN)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 143 AND `phone_format` = ''; -- Montserrat (MS)
UPDATE `oc_country` SET `phone_format` = '+212 X XX XX XX XX' WHERE `country_id` = 144 AND `phone_format` = ''; -- Morocco (MA)
UPDATE `oc_country` SET `phone_format` = '+258 XX XXX XXXX' WHERE `country_id` = 145 AND `phone_format` = ''; -- Mozambique (MZ)
UPDATE `oc_country` SET `phone_format` = '+264 XX XXX XXXX' WHERE `country_id` = 147 AND `phone_format` = ''; -- Namibia (NA)
UPDATE `oc_country` SET `phone_format` = '+674 XXX XXXX' WHERE `country_id` = 148 AND `phone_format` = ''; -- Nauru (NR)
UPDATE `oc_country` SET `phone_format` = '+977 XXX-XXXXXXX' WHERE `country_id` = 149 AND `phone_format` = ''; -- Nepal (NP)
UPDATE `oc_country` SET `phone_format` = '+687 XX.XX.XX' WHERE `country_id` = 152 AND `phone_format` = ''; -- New Caledonia (NC)
UPDATE `oc_country` SET `phone_format` = '+505 XXXX XXXX' WHERE `country_id` = 154 AND `phone_format` = ''; -- Nicaragua (NI)
UPDATE `oc_country` SET `phone_format` = '+227 XX XX XX XX' WHERE `country_id` = 155 AND `phone_format` = ''; -- Niger (NE)
UPDATE `oc_country` SET `phone_format` = '+234 XXX XXX XXXX' WHERE `country_id` = 156 AND `phone_format` = ''; -- Nigeria (NG)
UPDATE `oc_country` SET `phone_format` = '+672 X XXXXX' WHERE `country_id` = 158 AND `phone_format` = ''; -- Norfolk Island (NF)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 159 AND `phone_format` = ''; -- Northern Mariana Islands (MP)
UPDATE `oc_country` SET `phone_format` = '+47 XX XX XX XX' WHERE `country_id` = 160 AND `phone_format` = ''; -- Norway (NO)
UPDATE `oc_country` SET `phone_format` = '+968 XXXX XXXX' WHERE `country_id` = 161 AND `phone_format` = ''; -- Oman (OM)
UPDATE `oc_country` SET `phone_format` = '+92 XXX XXXXXXX' WHERE `country_id` = 162 AND `phone_format` = ''; -- Pakistan (PK)
UPDATE `oc_country` SET `phone_format` = '+680 XXX XXXX' WHERE `country_id` = 163 AND `phone_format` = ''; -- Palau (PW)
UPDATE `oc_country` SET `phone_format` = '+675 XXXX XXXX' WHERE `country_id` = 165 AND `phone_format` = ''; -- Papua New Guinea (PG)
UPDATE `oc_country` SET `phone_format` = '+595 XXX XXXXXX' WHERE `country_id` = 166 AND `phone_format` = ''; -- Paraguay (PY)
UPDATE `oc_country` SET `phone_format` = '+51 XXX XXX XXX' WHERE `country_id` = 167 AND `phone_format` = ''; -- Peru (PE)
UPDATE `oc_country` SET `phone_format` = '+63 XXX XXX XXXX' WHERE `country_id` = 168 AND `phone_format` = ''; -- Philippines (PH)
UPDATE `oc_country` SET `phone_format` = '+48 XXX XXX XXX' WHERE `country_id` = 170 AND `phone_format` = ''; -- Poland (PL)
UPDATE `oc_country` SET `phone_format` = '+351 XXX XXX XXX' WHERE `country_id` = 171 AND `phone_format` = ''; -- Portugal (PT)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 172 AND `phone_format` = ''; -- Puerto Rico (PR)
UPDATE `oc_country` SET `phone_format` = '+974 XXXX XXXX' WHERE `country_id` = 173 AND `phone_format` = ''; -- Qatar (QA)
UPDATE `oc_country` SET `phone_format` = '+262 XXX XX XX XX' WHERE `country_id` = 174 AND `phone_format` = ''; -- Reunion (RE)
UPDATE `oc_country` SET `phone_format` = '+40 XXX XXX XXX' WHERE `country_id` = 175 AND `phone_format` = ''; -- Romania (RO)
UPDATE `oc_country` SET `phone_format` = '+7 XXX XXX-XX-XX' WHERE `country_id` = 176 AND `phone_format` = ''; -- Russian Federation (RU)
UPDATE `oc_country` SET `phone_format` = '+250 XXX XXX XXX' WHERE `country_id` = 177 AND `phone_format` = ''; -- Rwanda (RW)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 178 AND `phone_format` = ''; -- Saint Kitts and Nevis (KN)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 179 AND `phone_format` = ''; -- Saint Lucia (LC)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 180 AND `phone_format` = ''; -- Saint Vincent and the Grenadines (VC)
UPDATE `oc_country` SET `phone_format` = '+378 XX XX XX XX' WHERE `country_id` = 182 AND `phone_format` = ''; -- San Marino (SM)
UPDATE `oc_country` SET `phone_format` = '+239 XXX XXXX' WHERE `country_id` = 183 AND `phone_format` = ''; -- Sao Tome and Principe (ST)
UPDATE `oc_country` SET `phone_format` = '+966 XX XXX XXXX' WHERE `country_id` = 184 AND `phone_format` = ''; -- Saudi Arabia (SA)
UPDATE `oc_country` SET `phone_format` = '+221 XX XXX XX XX' WHERE `country_id` = 185 AND `phone_format` = ''; -- Senegal (SN)
UPDATE `oc_country` SET `phone_format` = '+248 X XXX XXX' WHERE `country_id` = 186 AND `phone_format` = ''; -- Seychelles (SC)
UPDATE `oc_country` SET `phone_format` = '+232 XX XXXXXX' WHERE `country_id` = 187 AND `phone_format` = ''; -- Sierra Leone (SL)
UPDATE `oc_country` SET `phone_format` = '+65 XXXX XXXX' WHERE `country_id` = 188 AND `phone_format` = ''; -- Singapore (SG)
UPDATE `oc_country` SET `phone_format` = '+421 XXX XXX XXX' WHERE `country_id` = 189 AND `phone_format` = ''; -- Slovak Republic (SK)
UPDATE `oc_country` SET `phone_format` = '+386 XX XXX XXX' WHERE `country_id` = 190 AND `phone_format` = ''; -- Slovenia (SI)
UPDATE `oc_country` SET `phone_format` = '+34 XXX XX XX XX' WHERE `country_id` = 195 AND `phone_format` = ''; -- Spain (ES)
UPDATE `oc_country` SET `phone_format` = '+94 XX XXX XXXX' WHERE `country_id` = 196 AND `phone_format` = ''; -- Sri Lanka (LK)
UPDATE `oc_country` SET `phone_format` = '+290 XXXXX' WHERE `country_id` = 197 AND `phone_format` = ''; -- St. Helena (SH)
UPDATE `oc_country` SET `phone_format` = '+249 XX XXX XXXX' WHERE `country_id` = 199 AND `phone_format` = ''; -- Sudan (SD)
UPDATE `oc_country` SET `phone_format` = '+597 XXX-XXXX' WHERE `country_id` = 200 AND `phone_format` = ''; -- Suriname (SR)
UPDATE `oc_country` SET `phone_format` = '+47 XXXXXXXX' WHERE `country_id` = 201 AND `phone_format` = ''; -- Svalbard and Jan Mayen Islands (SJ)
UPDATE `oc_country` SET `phone_format` = '+268 XXXX XXXX' WHERE `country_id` = 202 AND `phone_format` = ''; -- Swaziland (SZ)
UPDATE `oc_country` SET `phone_format` = '+46 XX-XXX XX XX' WHERE `country_id` = 203 AND `phone_format` = ''; -- Sweden (SE)
UPDATE `oc_country` SET `phone_format` = '+41 XX XXX XX XX' WHERE `country_id` = 204 AND `phone_format` = ''; -- Switzerland (CH)
UPDATE `oc_country` SET `phone_format` = '+963 XXX XXX XXX' WHERE `country_id` = 205 AND `phone_format` = ''; -- Syrian Arab Republic (SY)
UPDATE `oc_country` SET `phone_format` = '+886 XXX XXX XXX' WHERE `country_id` = 206 AND `phone_format` = ''; -- Taiwan (TW)
UPDATE `oc_country` SET `phone_format` = '+992 XX XXX XXXX' WHERE `country_id` = 207 AND `phone_format` = ''; -- Tajikistan (TJ)
UPDATE `oc_country` SET `phone_format` = '+255 XXX XXX XXX' WHERE `country_id` = 208 AND `phone_format` = ''; -- Tanzania, United Republic of (TZ)
UPDATE `oc_country` SET `phone_format` = '+66 XX XXX XXXX' WHERE `country_id` = 209 AND `phone_format` = ''; -- Thailand (TH)
UPDATE `oc_country` SET `phone_format` = '+228 XX XX XX XX' WHERE `country_id` = 210 AND `phone_format` = ''; -- Togo (TG)
UPDATE `oc_country` SET `phone_format` = '+676 XXX XXXX' WHERE `country_id` = 212 AND `phone_format` = ''; -- Tonga (TO)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 213 AND `phone_format` = ''; -- Trinidad and Tobago (TT)
UPDATE `oc_country` SET `phone_format` = '+216 XX XXX XXX' WHERE `country_id` = 214 AND `phone_format` = ''; -- Tunisia (TN)
UPDATE `oc_country` SET `phone_format` = '+90 XXX XXX XX XX' WHERE `country_id` = 215 AND `phone_format` = ''; -- Turkey (TR)
UPDATE `oc_country` SET `phone_format` = '+993 XX XXXXXX' WHERE `country_id` = 216 AND `phone_format` = ''; -- Turkmenistan (TM)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 217 AND `phone_format` = ''; -- Turks and Caicos Islands (TC)
UPDATE `oc_country` SET `phone_format` = '+256 XXX XXXXXX' WHERE `country_id` = 219 AND `phone_format` = ''; -- Uganda (UG)
UPDATE `oc_country` SET `phone_format` = '+380 XX XXX XXXX' WHERE `country_id` = 220 AND `phone_format` = ''; -- Украина (UA)
UPDATE `oc_country` SET `phone_format` = '+971 XX XXX XXXX' WHERE `country_id` = 221 AND `phone_format` = ''; -- United Arab Emirates (AE)
UPDATE `oc_country` SET `phone_format` = '+44 XXXX XXXXXX' WHERE `country_id` = 222 AND `phone_format` = ''; -- United Kingdom (GB)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 223 AND `phone_format` = ''; -- United States (US)
UPDATE `oc_country` SET `phone_format` = '+598 XX XXX XXX' WHERE `country_id` = 225 AND `phone_format` = ''; -- Uruguay (UY)
UPDATE `oc_country` SET `phone_format` = '+998 XX XXX XX XX' WHERE `country_id` = 226 AND `phone_format` = ''; -- Uzbekistan (UZ)
UPDATE `oc_country` SET `phone_format` = '+678 XXX XXXX' WHERE `country_id` = 227 AND `phone_format` = ''; -- Vanuatu (VU)
UPDATE `oc_country` SET `phone_format` = '+58 XXX-XXXXXXX' WHERE `country_id` = 229 AND `phone_format` = ''; -- Venezuela (VE)
UPDATE `oc_country` SET `phone_format` = '+84 XXX XXX XXX' WHERE `country_id` = 230 AND `phone_format` = ''; -- Viet Nam (VN)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 231 AND `phone_format` = ''; -- Virgin Islands (British) (VG)
UPDATE `oc_country` SET `phone_format` = '+1 (XXX) XXX-XXXX' WHERE `country_id` = 232 AND `phone_format` = ''; -- Virgin Islands (U.S.) (VI)
UPDATE `oc_country` SET `phone_format` = '+681 XX XX XX' WHERE `country_id` = 233 AND `phone_format` = ''; -- Wallis and Futuna Islands (WF)
UPDATE `oc_country` SET `phone_format` = '+212 XXXXXXXXX' WHERE `country_id` = 234 AND `phone_format` = ''; -- Western Sahara (EH)
UPDATE `oc_country` SET `phone_format` = '+967 XXX XXX XXX' WHERE `country_id` = 235 AND `phone_format` = ''; -- Yemen (YE)
UPDATE `oc_country` SET `phone_format` = '+260 XX XXXXXXX' WHERE `country_id` = 238 AND `phone_format` = ''; -- Zambia (ZM)
UPDATE `oc_country` SET `phone_format` = '+263 XX XXX XXXX' WHERE `country_id` = 239 AND `phone_format` = ''; -- Zimbabwe (ZW)
UPDATE `oc_country` SET `phone_format` = '+382 XX XXX XXX' WHERE `country_id` = 242 AND `phone_format` = ''; -- Montenegro (ME)
UPDATE `oc_country` SET `phone_format` = '+599 XXXXXXX' WHERE `country_id` = 245 AND `phone_format` = ''; -- Bonaire, Sint Eustatius and Saba (BQ)
UPDATE `oc_country` SET `phone_format` = '+970 XXX XXX XXX' WHERE `country_id` = 247 AND `phone_format` = ''; -- Palestinian Territory, Occupied (PS)
UPDATE `oc_country` SET `phone_format` = '+211 XXX XXX XXX' WHERE `country_id` = 248 AND `phone_format` = ''; -- South Sudan (SS)
UPDATE `oc_country` SET `phone_format` = '+590 XXXXXXXXX' WHERE `country_id` = 249 AND `phone_format` = ''; -- St. Barthelemy (BL)
UPDATE `oc_country` SET `phone_format` = '+590 XXXXXXXXX' WHERE `country_id` = 250 AND `phone_format` = ''; -- St. Martin (French part) (MF)
UPDATE `oc_country` SET `phone_format` = '+34 XXX XX XX XX' WHERE `country_id` = 251 AND `phone_format` = ''; -- Canary Islands (IC)
UPDATE `oc_country` SET `phone_format` = '+247 XXXXX' WHERE `country_id` = 252 AND `phone_format` = ''; -- Ascension Island (British) (AC)
UPDATE `oc_country` SET `phone_format` = '+383 XX XXX XXX' WHERE `country_id` = 253 AND `phone_format` = ''; -- Kosovo, Republic of (XK)
UPDATE `oc_country` SET `phone_format` = '+44 XXXXXXXXXX' WHERE `country_id` = 254 AND `phone_format` = ''; -- Isle of Man (IM)
UPDATE `oc_country` SET `phone_format` = '+290 XXXX' WHERE `country_id` = 255 AND `phone_format` = ''; -- Tristan da Cunha (TA)
UPDATE `oc_country` SET `phone_format` = '+44 XXXXXXXXXX' WHERE `country_id` = 256 AND `phone_format` = ''; -- Guernsey (GG)
UPDATE `oc_country` SET `phone_format` = '+44 XXXXXXXXXX' WHERE `country_id` = 257 AND `phone_format` = ''; -- Jersey (JE)

-- Per-language address formats: inherit base where empty
UPDATE `oc_country_description` cd
JOIN `oc_country` c ON c.`country_id` = cd.`country_id`
SET cd.`address_format` = c.`address_format`
WHERE cd.`address_format` = '' AND c.`address_format` <> '';
